#ifndef __ZFW_INPUT_CODES_H__
#define __ZFW_INPUT_CODES_H__

typedef enum
{
	ZFW_KEY_CODE_SPACE,

	ZFW_KEY_CODE_0,
	ZFW_KEY_CODE_1,
	ZFW_KEY_CODE_2,
	ZFW_KEY_CODE_3,
	ZFW_KEY_CODE_4,
	ZFW_KEY_CODE_5,
	ZFW_KEY_CODE_6,
	ZFW_KEY_CODE_7,
	ZFW_KEY_CODE_8,
	ZFW_KEY_CODE_9,

	ZFW_KEY_CODE_A,
	ZFW_KEY_CODE_B,
	ZFW_KEY_CODE_C,
	ZFW_KEY_CODE_D,
	ZFW_KEY_CODE_E,
	ZFW_KEY_CODE_F,
	ZFW_KEY_CODE_G,
	ZFW_KEY_CODE_H,
	ZFW_KEY_CODE_I,
	ZFW_KEY_CODE_J,
	ZFW_KEY_CODE_K,
	ZFW_KEY_CODE_L,
	ZFW_KEY_CODE_M,
	ZFW_KEY_CODE_N,
	ZFW_KEY_CODE_O,
	ZFW_KEY_CODE_P,
	ZFW_KEY_CODE_Q,
	ZFW_KEY_CODE_R,
	ZFW_KEY_CODE_S,
	ZFW_KEY_CODE_T,
	ZFW_KEY_CODE_U,
	ZFW_KEY_CODE_V,
	ZFW_KEY_CODE_W,
	ZFW_KEY_CODE_X,
	ZFW_KEY_CODE_Y,
	ZFW_KEY_CODE_Z,

	ZFW_KEY_CODE_ESCAPE,
	ZFW_KEY_CODE_ENTER,
	ZFW_KEY_CODE_TAB,

	ZFW_KEY_CODE_RIGHT,
	ZFW_KEY_CODE_LEFT,
	ZFW_KEY_CODE_DOWN,
	ZFW_KEY_CODE_UP,

	ZFW_KEY_CODE_F1,
	ZFW_KEY_CODE_F2,
	ZFW_KEY_CODE_F3,
	ZFW_KEY_CODE_F4,
	ZFW_KEY_CODE_F5,
	ZFW_KEY_CODE_F6,
	ZFW_KEY_CODE_F7,
	ZFW_KEY_CODE_F8,
	ZFW_KEY_CODE_F9,
	ZFW_KEY_CODE_F10,
	ZFW_KEY_CODE_F11,
	ZFW_KEY_CODE_F12,

	ZFW_KEY_CODE_LEFT_SHIFT,
	ZFW_KEY_CODE_LEFT_CONTROL,
	ZFW_KEY_CODE_LEFT_ALT,

	ZFW_NUM_KEY_CODES
} zfw_key_code_t;

typedef enum
{
	ZFW_MOUSE_BUTTON_CODE_LEFT,
	ZFW_MOUSE_BUTTON_CODE_RIGHT,
	ZFW_MOUSE_BUTTON_CODE_MIDDLE,

	ZFW_NUM_MOUSE_BUTTON_CODES
} zfw_mouse_button_code_t;

typedef enum
{
	ZFW_GAMEPAD_BUTTON_CODE_A,
	ZFW_GAMEPAD_BUTTON_CODE_B,
	ZFW_GAMEPAD_BUTTON_CODE_X,
	ZFW_GAMEPAD_BUTTON_CODE_Y,

	ZFW_GAMEPAD_BUTTON_CODE_LEFT_BUMPER,
	ZFW_GAMEPAD_BUTTON_CODE_RIGHT_BUMPER,

	ZFW_GAMEPAD_BUTTON_CODE_BACK,
	ZFW_GAMEPAD_BUTTON_CODE_START,
	ZFW_GAMEPAD_BUTTON_CODE_GUIDE,

	ZFW_GAMEPAD_BUTTON_CODE_LEFT_THUMB,
	ZFW_GAMEPAD_BUTTON_CODE_RIGHT_THUMB,

	ZFW_GAMEPAD_BUTTON_CODE_DPAD_UP,
	ZFW_GAMEPAD_BUTTON_CODE_DPAD_RIGHT,
	ZFW_GAMEPAD_BUTTON_CODE_DPAD_DOWN,
	ZFW_GAMEPAD_BUTTON_CODE_DPAD_LEFT,

	ZFW_NUM_GAMEPAD_BUTTON_CODES
} zfw_gamepad_button_code_t;

typedef enum
{
	ZFW_GAMEPAD_AXIS_CODE_LEFT_X,
	ZFW_GAMEPAD_AXIS_CODE_LEFT_Y,

	ZFW_GAMEPAD_AXIS_CODE_RIGHT_X,
	ZFW_GAMEPAD_AXIS_CODE_RIGHT_Y,

	ZFW_GAMEPAD_AXIS_CODE_LEFT_TRIGGER,
	ZFW_GAMEPAD_AXIS_CODE_RIGHT_TRIGGER,

	ZFW_NUM_GAMEPAD_AXIS_CODES
} zfw_gamepad_axis_code_t;

#endif
